### ISSUE TITLE
error worldguardextraflags

### ISSUE THREAD

**Issue by frogglen** [aromaa/WorldGuardExtraFlags#241]
```
[14:25:14] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to WorldGuardExtraFlags v4.2.1
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(com.sk89q.worldguard.protection.regions.ProtectedRegion)" because the return value of "com.sk89q.worldguard.protection.regions.RegionContainer.get(com.sk89q.worldedit.world.World)" is null
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.doUnloadChunkFlagCheck(WorldListener.java:49) ~[WorldGuardExtraFlags.jar:?]
	at net.goldtreeservers.worldguardextraflags.listeners.WorldListener.onChunkUnloadEvent(WorldListener.java:44) ~[WorldGuardExtraFlags.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1091.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1933]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.unloadCallback(LevelChunk.java:963) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkUnload(LevelChunk.java:891) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleTickingState(ChunkTaskScheduler.java:293) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleChunkLoad(ChunkTaskScheduler.java:399) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:537) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:444) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:652) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:931) ~[?:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:121) ~[?:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:79) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:63) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:45) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:1787) ~[?:?]
	at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2402) ~[?:?]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:788) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:755) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:663) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.setTypeAndData(CraftBlock.java:212) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.setTypeAndData(CraftBlock.java:197) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.setBlockData(CraftBlock.java:193) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.setType(CraftBlock.java:182) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftBlock.setType(CraftBlock.java:176) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at com.magmaguy.elitemobs.instanced.InstanceDeathLocation.clear(InstanceDeathLocation.java:59) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.instanced.InstancePlayerManager.removeSpectator(InstancePlayerManager.java:164) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.instanced.MatchInstance.removeSpectator(MatchInstance.java:116) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.instanced.InstancePlayerManager.removeAnyKind(InstancePlayerManager.java:169) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.instanced.MatchInstance.removeAnyKind(MatchInstance.java:120) ~[EliteMobs.jar:?]
	at com.magmaguy.elitemobs.commands.UserCommands.lambda$new$30(UserCommands.java:346) ~[EliteMobs.jar:?]
	at com.magmaguy.shaded.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[EliteMobs.jar:?]
	at com.magmaguy.shaded.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[EliteMobs.jar:?]
	at com.magmaguy.shaded.cloud.CommandManager.executeCommand(CommandManager.java:188) ~[EliteMobs.jar:?]
	at com.magmaguy.shaded.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[EliteMobs.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by aromaa** [comment]
Fixed in 3814ca9219b3aeaa70d5615f66871b996a31812f
