### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by darealblack** [aromaa/WorldGuardExtraFlags#255]
My console gets spammed with:
```
`[13:41:58 WARN]: Task #44 for WorldGuard v7.0.8+33cdb4a generated an exception
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/ApplicableRegionSet
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2053) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956) ~[guava-31.0.1-jre.jar:?]
	at com.sk89q.worldguard.session.AbstractSessionManager.get(AbstractSessionManager.java:169) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.run(BukkitSessionManager.java:71) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1735]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1518) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1209) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/ApplicableRegionSet
	at net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler.initialize(CommandOnExitFlagHandler.java:48) ~[WorldGuardExtraFlags.jar:?]
	at com.sk89q.worldguard.session.Session.initialize(Session.java:119) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.session.AbstractSessionManager.createSession(AbstractSessionManager.java:178) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$2(AbstractSessionManager.java:73) ~[worldguard-bukkit-7.0.7-dist.jar:?]
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar:?]
	... 14 more
`
```

This happens in 1.19:
With the latest build of FastAsyncWorldEdit, WorldGuardExtraFlags
WorldGuard 7.07*

**Comment by aromaa** [comment]
You have either reloaded the plugin or you have corrupted plugins.
