### ISSUE TITLE
Incompatibility with AdvancedSlimePaper and Slime World Manager

### ISSUE THREAD

**Issue by VideoGameSmash12** [aromaa/WorldGuardExtraFlags#256]
We are using a server that uses patches from AdvancedSlimePaper and the Slime World Manager plugin. When the plugin is installed alongside Slime World Manager, it fails to set itself up properly and spams the logs.

Stacktrace:
```none
[04:14:50] [Server thread/ERROR]: Error occurred while enabling WorldGuardExtraFlags v4.2.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.protection.managers.RegionManager.getRegions()" because the return value of "com.sk89q.worldguard.protection.regions.RegionContainer.get(com.sk89q.worldedit.world.World)" is null
	at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.doUnloadChunkFlagCheck(WorldGuardExtraFlagsPlugin.java:158) ~[WorldGuardExtraFlags.jar:?]
	at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:150) ~[WorldGuardExtraFlags.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[scissors-1.20.1.jar:git-Scissors-11]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[scissors-1.20.1.jar:git-Scissors-11]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[scissors-1.20.1.jar:git-Scissors-11]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[scissors-1.20.1.jar:git-Scissors-11]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[scissors-1.20.1.jar:git-Scissors-11]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[scissors-1.20.1.jar:git-Scissors-11]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[scissors-1.20.1.jar:git-Scissors-11]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[scissors-1.20.1.jar:git-Scissors-11]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[scissors-1.20.1.jar:git-Scissors-11]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by VideoGameSmash12** [comment]
Oh apparently you need to do some wacky WorldLoadEvent quackery for it to work. Discard this.
