### ISSUE TITLE
Error occurred while enabling WorldGuardExtraFlags v4.2.2

### ISSUE THREAD

**Issue by xbette** [aromaa/WorldGuardExtraFlags#262]
After updating to 
- worldguard-bukkit-7.0.10-SNAPSHOT-dist
- worldedit-bukkit-7.2.17
- WorldGuard Extra Flags 4.2.2

then im getting error when a user is loggin in to the server. 
Running paper 1.20.2

Even under load of server i got error with worldguardextraflags

`[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler
ERROR
Error occurred while enabling WorldGuardExtraFlags v4.2.2 (Is it up to date?)
Console
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
at net.goldtreeservers.worldguardextraflags.protocollib.ProtocolLibHelper.onEnable(ProtocolLibHelper.java:23) ~[WorldGuardExtraFlags.jar:?]
at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:142) ~[WorldGuardExtraFlags.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-241]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 14 more
INFO
[WorldGuardExtraFlags]: Disabling WorldGuardExtraFlags v4.2.2`

`[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.WalkSpeedFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.BlockedEffectsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GodmodeFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GiveEffectsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlyFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.FlySpeedFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.PlaySoundsFlagHandler
[WorldGuard]: Registering session handler net.goldtreeservers.worldguardextraflags.wg.handlers.GlideFlagHandler
ERROR
Error occurred while enabling WorldGuardExtraFlags v4.2.2 (Is it up to date?)
Console
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
at net.goldtreeservers.worldguardextraflags.protocollib.ProtocolLibHelper.onEnable(ProtocolLibHelper.java:23) ~[WorldGuardExtraFlags.jar:?]
at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:142) ~[WorldGuardExtraFlags.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-241]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 14 more
INFO
[WorldGuardExtraFlags]: Disabling WorldGuardExtraFlags v4.2.2
[CoreProtect]: Enabling CoreProtect v22.2
[HeadDatabase]: Successfully loaded 57109 heads!
[CoreProtect]: CoreProtect has been successfully enabled!
[CoreProtect]: Using SQLite for data storage.

[CoreProtect]: Enjoy CoreProtect? Join our Discord!
[CoreProtect]: Discord: www.coreprotect.net/discord/

[ServerUtils]: Enabling ServerUtils v3.5.4
[HeadDatabase]: Successfully loaded 13 featured tags!
[Spyglass]: Enabling Spyglass v1.2.0*
[EnderDragon]: Enabling EnderDragon v2.2.1
[EnderDragon]: Enabling plugin...
[EnderDragon]: Author: Xanadu13
[EnderDragon]: Found version: v1_20_R2
[EnderDragon]: Hooking to PlaceholderAPI...
[PlaceholderAPI]: Successfully registered internal expansion: ed [2.2.1]
[EnderDragon]: Language: Danish
[EnderDragon]: Checking update...
[EnderDragon]: File Danish.yml is out of date，please update it.
[EnderDragon]: File config.yml is out of date，please update it.
[EnderDragon]: File data.yml is out of date，please update it.
[EnderDragon]: You can use /ed update to update the config!
[LiteBans]: Enabling LiteBans v2.12.5
[LiteBans]: Using default database drivers (version:8).
[LiteBans]: Using system locale (en)
[LiteBans]: Loaded 4 templates from templates.yml!
WARN
[LiteBans]: Failed to add ProtocolLib packet listener.
INFO
[LiteBans]: Loading SQL driver: mysql 8.0.29 (com.mysql.cj.jdbc.Driver)
[LiteBans]: Connecting to database...
[LiteBans]: litebans-pool - Starting...
[LiteBans]: litebans-pool - Start completed.
[LiteBans]: Connected to MySQL database successfully (117.6 ms).
[LiteBans]: Database connection fully initialized (127.3 ms).
[LiteBans]: v2.12.5 enabled. Startup took 223 ms.
[Wild]: Enabling Wild v2.29-7da6164
[ViaBackwards]: Enabling ViaBackwards v4.8.1
[spark]: Enabling spark v1.10.43
[spark]: Using Paper ServerTickStartEvent for tick monitoring
[spark]: Starting background profiler...
[PlaceholderAPI]: Successfully registered internal expansion: spark [1.10.43]
[spark]: Registered PlaceholderAPI placeholders
[CommandSpy]: Enabling CommandSpy v2.0*
[PlaceholderAPI]: Placeholder expansion registration initializing...
Running delayed init tasks
[Essentials]: Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[CoreProtect]: WorldEdit logging successfully initialized.
[Essentials]: Fetching version information...
[Essentials]: Update checking disabled in config.
[ViaVersion]: Finished mapping loading, shutting down loader executor!
[ServerUtils]: Checking for updates...
Done (12.618s)! For help, type "help"
Timings Reset
[EnderDragon]: Reading file view.yml
[Vault]: Checking for Updates ...
[EnderDragon]: File default.yml is out of date，please update it.
[EnderDragon]: File special.yml is out of date，please update it.
[Vault]: No new version available
[PlaceholderAPI]: Successfully registered external expansion: luckperms [5.1-R2]
[PlaceholderAPI]: Successfully registered external expansion: essentials [1.4.0]
[PlaceholderAPI]: Successfully registered external expansion: vault [1.7.0]
[PlaceholderAPI]: Successfully registered external expansion: Advancements [1.7]
[PlaceholderAPI]: Successfully registered external expansion: statistic [2.0.1]
[PlaceholderAPI]: Successfully registered external expansion: player [2.0.2]
[PlaceholderAPI]: Successfully registered external expansion: parseother [1.4.1]
[PlaceholderAPI]: Successfully registered external expansion: server [2.6.0]
WARN
[PlaceholderAPI]: There was an issue with loading an expansion.
INFO
8 placeholder hook(s) registered! 6 placeholder hook(s) have an update available.
[ServerUtils]: We are up-to-date!
[EnderDragon]: You are using the latest version (v2.2.1)...
[CustomCommands]: Loaded command playtime, now registering it on spigot command map...
[CustomCommands]: Loaded command played, now registering it on spigot command map...
[CustomCommands]: Loaded command joined, now registering it on spigot command map...
[CustomCommands]: Loaded command sletdyr, now registering it on spigot command map...
[EnderDragon]: 0 auto_respawn task(s) started to run...
Console
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler.initialize(CommandOnExitFlagHandler.java:48) ~[WorldGuardExtraFlags.jar:?]
at com.sk89q.worldguard.session.Session.initialize(Session.java:119) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.createSession(AbstractSessionManager.java:178) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$2(AbstractSessionManager.java:73) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
... 40 more
INFO
Bette_: logged in with entity id 104 at ([world]-1683.5, 78.0, -2082.5)
WARN
[WorldGuard]: Task #12 for WorldGuard v7.0.10-SNAPSHOT+2260-c7319f1 generated an exception
Console
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: zip file closed
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.get(AbstractSessionManager.java:169) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.run(BukkitSessionManager.java:71) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-241]
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-241]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-241]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.goldtreeservers.worldguardextraflags.wg.handlers.CommandOnExitFlagHandler.initialize(CommandOnExitFlagHandler.java:48) ~[WorldGuardExtraFlags.jar:?]
at com.sk89q.worldguard.session.Session.initialize(Session.java:119) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.createSession(AbstractSessionManager.java:178) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$2(AbstractSessionManager.java:73) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist.jar:?]
at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
... 14 more
WARN
INFO
[WorldEdit]: Disabling WorldEdit v7.2.17+6544-56d0383
Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[Vault]: Disabling Vault v1.7.3-b131
[LuckPerms]: Disabling LuckPerms v5.4.104
[LuckPerms]: Starting shutdown process...
[LuckPerms]: Closing storage...
[LuckPerms]: Goodbye!
[ViaVersion]: Disabling ViaVersion v4.8.1
[ViaVersion]: ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
Saving players
Bette_ lost connection:
Bette_ left the game
Saving worlds
Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[ChunkHolderManager]: Waiting 60s for chunk system to halt for world 'world'
[ChunkHolderManager]: Halted chunk system for world 'world'
[ChunkHolderManager]: Saving all chunkholders for world 'world'
[ChunkHolderManager]: Saved 625 block chunks, 625 entity chunks, 0 poi chunks in world 'world' in 0.59s
ThreadedAnvilChunkStorage (world): All chunks are saved
Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[ChunkHolderManager]: Waiting 60s for chunk system to halt for world 'world_nether'
[ChunkHolderManager]: Halted chunk system for world 'world_nether'
[ChunkHolderManager]: Saving all chunkholders for world 'world_nether'
[ChunkHolderManager]: Saved 529 block chunks, 529 entity chunks, 0 poi chunks in world 'world_nether' in 0.36s
ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[ChunkHolderManager]: Waiting 60s for chunk system to halt for world 'world_the_end'
[ChunkHolderManager]: Halted chunk system for world 'world_the_end'
[ChunkHolderManager]: Saving all chunkholders for world 'world_the_end'
[ChunkHolderManager]: Saved 529 block chunks, 529 entity chunks, 0 poi chunks in world 'world_the_end' in 0.07s
ThreadedAnvilChunkStorage (DIM1): All chunks are saved
ThreadedAnvilChunkStorage: All dimensions are saved
Flushing Chunk IO
Closing Thread Pool
Closing Server
`

**Comment by xbette** [comment]
NVM. Postet on spigot instead!
