### ISSUE TITLE
[issue] compatability issue?

### ISSUE THREAD

**Issue by anthony1204** [aromaa/WorldGuardExtraFlags#263]
i installed mapmanager api and packetlistner api and now worldeditextra flags is not working. its red when i type /plugins
server logs:
```
[19:43:21 INFO]: [WorldGuardExtraFlags] Enabling WorldGuardExtraFlags v4.2.2

[19:43:21 ERROR]: Error occurred while enabling WorldGuardExtraFlags v4.2.2 (Is it up to date?)

java.lang.NullPointerException: Cannot invoke "com.sk89q.worldguard.WorldGuard.getPlatform()" because "this.worldGuard" is null

at net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin.onEnable(WorldGuardExtraFlagsPlugin.java:115) ~[WorldGuardExtraFlags.jar:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-36]

at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.reload(CraftServer.java:1043) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.Bukkit.reload(Bukkit.java:950) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:933) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1000) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at ch.njol.skript.Skript.dispatchCommand(Skript.java:1523) ~[Skript2.jar:?]

at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:82) ~[Skript2.jar:?]

at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[Skript2.jar:?]

at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:62) ~[Skript2.jar:?]

at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:90) ~[Skript2.jar:?]

at ch.njol.skript.lang.Trigger.execute(Trigger.java:52) ~[Skript2.jar:?]

at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:316) ~[Skript2.jar:?]

at ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:275) ~[Skript2.jar:?]

at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:286) ~[Skript2.jar:?]

at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:221) ~[Skript2.jar:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:933) ~[paper-1.20.1.jar:git-Paper-36]

at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-36]

at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2298) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2258) ~[?:?]

at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]

at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-36]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-36]

at java.lang.Thread.run(Thread.java:833) ~[?:?]

[19:43:21 INFO]: [WorldGuardExtraFlags] Disabling WorldGuardExtraFlags v4.2.2
```

**Comment by anthony1204** [comment]
i will try a server restart

**Comment by anthony1204** [comment]
oh, sorry false alarm. just needed a restart!

**Comment by anthony1204** [comment]
still wonder why it says that tho
